"""Read and clean EDGAR 10-K filing HTML/XHTML into an lxml tree.

Responsibilities (wave 2a contract, deliverable 1):
- read bytes (transparently through gzip for ``.htm.gz``)
- strip a leading XML declaration
- parse with lxml
- delete ``ix:header`` / ``ix:hidden`` entirely
- unwrap every other ``ix:*`` element so its text stays in place
- remove ``<script>``, ``<style>``, and comments
- keep ``<table>`` elements intact for wave 2b
- record every ``ix:nonFraction`` element (text, name, contextref, scale,
  sign, document order) before the tree is mutated, since wave 2b needs the
  full list (including facts that live inside ``ix:hidden``) for the
  coverage check.
"""

from __future__ import annotations

import gzip
import re
from pathlib import Path

from lxml import etree
from lxml import html as lxml_html

XML_DECL_RE = re.compile(rb"^\s*<\?xml[^>]*\?>\s*")

# lxml's HTML parser lowercases tag names but does not resolve namespaces,
# so an inline-XBRL tag like ``<ix:nonFraction>`` comes through the tree as
# the literal (lowercased) tag name ``ix:nonfraction``.
IX_DROP_TAGS = ("ix:header", "ix:hidden")
IX_PREFIX = "ix:"


def read_bytes(path: str | Path) -> bytes:
    """Read a filing's raw bytes, transparently decompressing ``.gz``."""
    path = Path(path)
    if path.name.endswith(".gz"):
        with gzip.open(path, "rb") as fh:
            return fh.read()
    return path.read_bytes()


def strip_xml_declaration(data: bytes) -> bytes:
    return XML_DECL_RE.sub(b"", data, count=1)


def parse_html(data: bytes):
    """Parse filing bytes into an lxml.html tree, recovering from errors."""
    data = strip_xml_declaration(data)
    parser = lxml_html.HTMLParser(recover=True, huge_tree=True)
    try:
        tree = lxml_html.fromstring(data, parser=parser)
    except Exception:
        # Fall back to a recovering XML parser for badly malformed XHTML,
        # then re-parse the serialized result as HTML so the rest of the
        # pipeline always deals with an lxml.html tree.
        xml_parser = etree.XMLParser(recover=True, huge_tree=True)
        root = etree.fromstring(data, parser=xml_parser)
        tree = lxml_html.fromstring(etree.tostring(root), parser=parser)
    return tree


def _norm_text(el) -> str:
    return " ".join(el.text_content().split())


def collect_nonfraction_records(tree) -> list[dict]:
    """Record every ix:nonFraction element before the tree is mutated.

    Returns a list of dicts in document order: text, name, contextref,
    scale, sign, order (1-based). This runs on the tree as parsed, so it
    also captures facts nested inside ix:header/ix:hidden (present in the
    filing but not necessarily visible in the cleaned prose/table text) --
    wave 2b's coverage check needs the full universe of facts, and reports
    the unmatched ones rather than the parser silently excluding them.
    """
    records: list[dict] = []
    order = 0
    for el in tree.iter():
        tag = el.tag
        if not isinstance(tag, str):
            continue
        if tag.lower() == "ix:nonfraction":
            order += 1
            records.append(
                {
                    "text": _norm_text(el),
                    "name": el.get("name"),
                    "contextref": el.get("contextref"),
                    "scale": el.get("scale"),
                    "sign": el.get("sign"),
                    "order": order,
                }
            )
    return records


def _remove_node_keep_tail(node) -> None:
    """Remove ``node`` from its parent without losing its tail text.

    lxml's ``Element.remove()`` discards the removed node's tail text along
    with it. Some EDGAR generators (CompSci Transform) place real content,
    such as a printed page number, as the tail of a comment (for example
    ``<!-- Field: PageNo -->i<!-- Field: /Sequence -->``), so a naive
    ``parent.remove(node)`` would silently delete that text.
    """
    parent = node.getparent()
    if parent is None:
        return
    tail = node.tail
    prev = node.getprevious()
    parent.remove(node)
    if tail:
        if prev is not None:
            prev.tail = (prev.tail or "") + tail
        else:
            parent.text = (parent.text or "") + tail


def clean_tree(tree):
    """Mutate ``tree`` in place per the cleaning rules. Returns ``tree``."""
    # Comments (including the generator banners like "Generated by
    # CompSci Transform"). Some generators put real text as a comment's
    # tail, so removal must preserve it.
    for c in tree.xpath("//comment()"):
        _remove_node_keep_tail(c)

    # <script> / <style>: drop entirely, they carry no citable text and
    # their tail text is real body content that must be kept.
    etree.strip_elements(tree, "script", "style", with_tail=False)

    # ix:header / ix:hidden: drop entirely (their tail is real content).
    for tagname in IX_DROP_TAGS:
        etree.strip_elements(tree, tagname, with_tail=False)

    # Every other ix:* element: unwrap, keeping text/tail/children in place.
    ix_tags = set()
    for el in tree.iter():
        tag = el.tag
        if isinstance(tag, str) and tag.lower().startswith(IX_PREFIX):
            ix_tags.add(tag)
    if ix_tags:
        etree.strip_tags(tree, *ix_tags)

    return tree


def clean_document(path: str | Path):
    """Read + parse + clean a filing. Returns (tree, ix_nonfraction_records)."""
    data = read_bytes(path)
    tree = parse_html(data)
    records = collect_nonfraction_records(tree)
    clean_tree(tree)
    return tree, records
